namespace KeyControl2.Features.Strings;

public static partial class HotStringsHandler{
	public const string Defaults="""
	                             [
	                                {
	                                    "Category":"AutoCorrect",
	                                    "Children":[
	                                        {
	                                            "Regex":"(?<=^| )itn$",
	                                            "IgnoreCase":false,
	                                            "Replacement":"int",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"flaot",
	                                            "To":"float",
	                                            "KeepCase":false,
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"laod",
	                                            "To":"load",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"nlul",
	                                            "To":"null",
	                                            "IgnoreCase":true,
	                                            "KeepCase":false,
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"cosnt",
	                                            "To":"const",
	                                            "KeepCase":false,
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"stlye",
	                                            "To":"style",
	                                            "KeepCase":false,
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "Regex":"(pin)t(out)$",
	                                            "IgnoreCase":true,
	                                            "Replacement":"$1$2",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "Regex":"(Wi)t(re)$",
	                                            "IgnoreCase":true,
	                                            "Replacement":"$1$2",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"druch",
	                                            "To":"durch",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"nixht",
	                                            "To":"nicht",
	                                            "Collapsed":true
	                                        }
	                                    ],
	                                    "Collapsed":true
	                                },
	                                {
	                                    "Category":"Unicode Coding",
	                                    "Children":[
	                                        {
	                                            "From":"@block",
	                                            "To":"█",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@full",
	                                            "To":"█",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@box",
	                                            "To":"█",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@root",
	                                            "To":"√",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@diameter",
	                                            "To":"⌀",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@durchmesser",
	                                            "To":"⌀",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@infinity",
	                                            "To":"∞",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@=>",
	                                            "To":"⇒",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@a-z",
	                                            "To":"abcdefghijklmnopqrstuvwxyz",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@A-Z",
	                                            "To":"ABCDEFGHIJKLMNOPQRSTUVWXYZ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@0-9",
	                                            "To":"0123456789",
	                                            "Collapsed":true
	                                        }
	                                    ],
	                                    "Collapsed":true
	                                },
	                                {
	                                    "Category":"Unicode Specials",
	                                    "Children":[
	                                        {
	                                            "From":"@zws",
	                                            "To":"​",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@space",
	                                            "To":"⠀",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@;",
	                                            "To":";",
	                                            "Collapsed":true
	                                        }
	                                    ],
	                                    "Collapsed":true
	                                },
	                                {
	                                    "Category":"Emojis",
	                                    "Children":[
	                                        {
	                                            "Emoji":"😂",
	                                            "From":"xdd",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "Emoji":"🙃",
	                                            "From":"rvv",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "Emoji":"❤",
	                                            "From":"hzz"
	                                        },
	                                        {
	                                            "Emoji":"🥺",
	                                            "From":"bgg",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "Emoji":"😘",
	                                            "From":"bss",
	                                            "Regex":"(?<!trie)(?<!Urlau)(?<!Kal)bss$",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "Emoji":"🙈",
	                                            "From":"@ape",
	                                            "Collapsed":true
	                                        }
	                                    ],
	                                    "Collapsed":true
	                                },
	                                {
	                                    "Category":"Greek",
	                                    "Enabled":false,
	                                    "Children":[
	                                        {
	                                            "From":"@Gamma",
	                                            "To":"Γ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Delta",
	                                            "To":"Δ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Theta",
	                                            "To":"Θ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Lambda",
	                                            "To":"Λ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Xi",
	                                            "To":"Ξ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Pi",
	                                            "To":"Π",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Rho",
	                                            "To":"Ρ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Sigma",
	                                            "To":"Σ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Sum",
	                                            "To":"Σ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Psi",
	                                            "To":"Ψ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Phi",
	                                            "To":"Φ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Omega",
	                                            "To":"Ω",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@Ohm",
	                                            "To":"Ω",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@alpha",
	                                            "To":"α",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@beta",
	                                            "To":"β",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@gamma",
	                                            "To":"γ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@delta",
	                                            "To":"δ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@epsilon",
	                                            "To":"ε",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@zeta",
	                                            "To":"ζ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@eta",
	                                            "To":"η",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@theta",
	                                            "To":"ϑ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@iota",
	                                            "To":"ι",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@kappa",
	                                            "To":"κ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@lamda",
	                                            "To":"λ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@lambda",
	                                            "To":"λ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@mu",
	                                            "To":"μ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@nu",
	                                            "To":"ν",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@xi",
	                                            "To":"ξ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@omicron",
	                                            "To":"ο",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@pi",
	                                            "To":"π",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@rho",
	                                            "To":"ρ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@final_sigma",
	                                            "To":"ς",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@sigma",
	                                            "To":"σ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@tau",
	                                            "To":"τ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@upsilon",
	                                            "To":"υ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@phi",
	                                            "To":"φ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@chi",
	                                            "To":"χ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@psi",
	                                            "To":"ψ",
	                                            "Collapsed":true
	                                        },
	                                        {
	                                            "From":"@omega",
	                                            "To":"ω",
	                                            "Collapsed":true
	                                        }
	                                    ],
	                                    "Collapsed":true
	                                }
	                             ]
	                             """;
}